// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=ts"
// @generated from file profilerequest/profilerequest.proto (package profilerequest, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file profilerequest/profilerequest.proto.
 */
export const file_profilerequest_profilerequest: GenFile = /*@__PURE__*/
  fileDesc("CiNwcm9maWxlcmVxdWVzdC9wcm9maWxlcmVxdWVzdC5wcm90bxIOcHJvZmlsZXJlcXVlc3QiIwoQU3Vic2NyaWJlUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJIpEBChNQcm9maWxlUmVxdWVzdEV2ZW50EhoKEnByb2ZpbGVfcmVxdWVzdF9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEg4KBnN0YXR1cxgDIAEoCRIVCg1yZXZpZXdlcl9ub3RlGAQgASgJEhIKCmNyZWF0ZWRfYXQYBSABKAkSEgoKdXBkYXRlZF9hdBgGIAEoCTJmCg5Qcm9maWxlUmVxdWVzdBJUCglTdWJzY3JpYmUSIC5wcm9maWxlcmVxdWVzdC5TdWJzY3JpYmVSZXF1ZXN0GiMucHJvZmlsZXJlcXVlc3QuUHJvZmlsZVJlcXVlc3RFdmVudDABYgZwcm90bzM");

/**
 * @generated from message profilerequest.SubscribeRequest
 */
export type SubscribeRequest = Message<"profilerequest.SubscribeRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message profilerequest.SubscribeRequest.
 * Use `create(SubscribeRequestSchema)` to create a new message.
 */
export const SubscribeRequestSchema: GenMessage<SubscribeRequest> = /*@__PURE__*/
  messageDesc(file_profilerequest_profilerequest, 0);

/**
 * @generated from message profilerequest.ProfileRequestEvent
 */
export type ProfileRequestEvent = Message<"profilerequest.ProfileRequestEvent"> & {
  /**
   * @generated from field: string profile_request_id = 1;
   */
  profileRequestId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string status = 3;
   */
  status: string;

  /**
   * @generated from field: string reviewer_note = 4;
   */
  reviewerNote: string;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 6;
   */
  updatedAt: string;
};

/**
 * Describes the message profilerequest.ProfileRequestEvent.
 * Use `create(ProfileRequestEventSchema)` to create a new message.
 */
export const ProfileRequestEventSchema: GenMessage<ProfileRequestEvent> = /*@__PURE__*/
  messageDesc(file_profilerequest_profilerequest, 1);

/**
 * @generated from service profilerequest.ProfileRequest
 */
export const ProfileRequest: GenService<{
  /**
   * @generated from rpc profilerequest.ProfileRequest.Subscribe
   */
  subscribe: {
    methodKind: "server_streaming";
    input: typeof SubscribeRequestSchema;
    output: typeof ProfileRequestEventSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_profilerequest_profilerequest, 0);

