// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=ts"
// @generated from file helloworld/helloworld.proto (package helloworld, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helloworld/helloworld.proto.
 */
export const file_helloworld_helloworld: GenFile = /*@__PURE__*/
  fileDesc("ChtoZWxsb3dvcmxkL2hlbGxvd29ybGQucHJvdG8SCmhlbGxvd29ybGQiHAoMSGVsbG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiHQoKSGVsbG9SZXBseRIPCgdtZXNzYWdlGAEgASgJMkkKB0dyZWV0ZXISPgoIU2F5SGVsbG8SGC5oZWxsb3dvcmxkLkhlbGxvUmVxdWVzdBoWLmhlbGxvd29ybGQuSGVsbG9SZXBseSIAQjAKG2lvLmdycGMuZXhhbXBsZXMuaGVsbG93b3JsZEIPSGVsbG9Xb3JsZFByb3RvUAFiBnByb3RvMw");

/**
 * The request message containing the user's name.
 *
 * @generated from message helloworld.HelloRequest
 */
export type HelloRequest = Message<"helloworld.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message helloworld.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema: GenMessage<HelloRequest> = /*@__PURE__*/
  messageDesc(file_helloworld_helloworld, 0);

/**
 * The response message containing the greetings
 *
 * @generated from message helloworld.HelloReply
 */
export type HelloReply = Message<"helloworld.HelloReply"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message helloworld.HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
export const HelloReplySchema: GenMessage<HelloReply> = /*@__PURE__*/
  messageDesc(file_helloworld_helloworld, 1);

/**
 * The greeting service definition.
 *
 * @generated from service helloworld.Greeter
 */
export const Greeter: GenService<{
  /**
   * Sends a greeting
   *
   * @generated from rpc helloworld.Greeter.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_helloworld_helloworld, 0);

