openapi: 3.1.0
info:
  title: cukiller api docs
  description: cukiller api docs
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /health:
    description: healthcheck
  /auth/register:
    post:
      summary: зарегать пользователя и получить свой auth_token
      responses:
        '200':
          description: here you go
  /auth/login:
    post:
      summary: Обновить свой auth_token
      description: Обновить свой auth_token
      responses:
        '200':
          description: here you go
  /auth/me:
    get:
      summary: получить полные данные о своем юзере имея только auth_token
      description: получить полные данные о своем юзере имея только auth_token
      responses:
        '200':
          description: данные
  /user/me:
    get:
      summary: литералли тоже самое, что и /auth/me
      description: литералли тоже самое, что и /auth/me
      responses:
        '200':
          description: данные
    put:
      summary: обновить данные о себе
      responses:
        '200':
          description: данные
  /users/{user_id}:
    get:
      summary: получить информацию о пользователе
      description: получить информацию о пользователе
      responses:
        '200':
          description: держи
    patch:
      summary: обновить пользователя (доступно только владельцу)
      responses:
        '200':
          description: обновили
    delete:
      summary: удалить пользователя (доступно только владельцу)
      responses:
        '204':
          description: NO_CONTENT, удалил
  /users/{left_user_id}/compare/{right_user_id}:
    get:
      summary: сравнить профили двух чуваков на схожесть
      description: сравнить профили двух чуваков на схожесть
      responses:
        '200':
          description: сравнил
  /system/profile-similarity:
    post:
      summary: сравнить профили двух чуваков на схожесть (литералли тоже самое)
      description: сравнить профили двух чуваков на схожесть
      responses:
        '200':
          description: сравнил
  /kills:
    get:
      summary: перечислить одобренные убийства
      description: перечислить одобренные убийства
      responses:
        '200':
          description: список
    post:
      summary: сообщить об убийстве
  /kills/my-pending:
    get:
      summary: список твоих убийств, ожидающих подтверждения
  /kills/{kill_id}/confirm:
    post:
      summary: подтвердить убийство
  /kills/{kill_id}/moderate:
    post:
      summary: промодерировать убийство
  /rankings:
    get:
      summary: лидерборд
  /stats/user/{user_id}:
    get:
      summary: получить
  /profile-creation-requests/{request_id}:
    get:
      summary: получить информацию
    patch:
      summary: обновить
    delete:
      summary: удалить
  /admin/users:
    get:
      summary: admin list users
    post:
      summary: admin create user
  /admin/users/{user_id}:
    get:
      summary: admin get user
    patch:
      summary: admin edit
    delete:
      summary: admin delete user
  /admin/profile-creation-requests:
    get:
      summary: admin get profile creation request
    patch:
      summary: admin update profile creation request
    delete:
      summary: admin delete profile creation request
